spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)